### ISSUE TITLE
"dpkg: error processing package openssh-server (--configure)" on apt install

### ISSUE THREAD

**Issue by mateus-amarante** [orise-robotics/ros2-docker-devel#21]
On any `apt install` or `apt upgrade` command I get this error. I think it is related to the fact we are sharing the ".ssh" folder. By the way, I think `openssh-server` should be added to the images

**Comment by ivan1993br** [comment]
humm.., .ssh folder usually contain nothing related to installation, just some user configuration

**Comment by ivan1993br** [comment]
THis problem is somehow related to [this one](https://github.com/orise-robotics/ros_ws/issues/12), because it tries to add a user `adduser: `/sbin/useradd -d /run/sshd -g nogroup -s /usr/sbin/nologin -u 130 sshd'` however the user folder is shored as :ro on the run. Maybe lets create the user on the container, to avoid all these errors?

**Comment by caioaamaral** [comment]
could you check how it behaves with #24 ?

**Comment by Charmve** [comment]
1 进入目录

cd /var/lib/dpkg

2 删除文件   

sudo mv info info.baksudo

3 重新创建

mkdir info

![image](https://user-images.githubusercontent.com/29084184/208219334-57a7551b-3940-4c18-a7f3-3c656a228f18.png)
